run:
  deadline: 5m
  skip-dirs:
    - vendor

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - godot

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/illiastavitskyi/qtest

issues:
  exclude-use-default: false
